# -*- coding: utf-8 -*-
"""assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hqlABys-cn5TKJFS3Lpuc4Kqm8RLkE2I
"""

from pygam import LinearGAM, s
import pandas as pd
import numpy as np

# Load training and test datasets
train_data = pd.read_csv("/content/assignment_data_train.csv")
test_data = pd.read_csv("/content/assignment_data_test.csv")

# Extract day of the week and modify hour values
for df in [train_data, test_data]:
    df['day_of_week_num'] = pd.to_datetime(df['Timestamp']).dt.weekday + 1
    df['hour_adjusted'] = df['hour'] + 1

# Define features and target variable
X_train = train_data[['month', 'day_of_week_num', 'hour_adjusted']].values
y_train = train_data['trips'].values

# Train the model and store it in modelFit
modelFit = LinearGAM(s(0) + s(1) + s(2)).gridsearch(X_train, y_train)

# Prepare test data and make predictions
X_test = test_data[['month', 'day_of_week_num', 'hour_adjusted']].values
test_data['trips'] = modelFit.predict(X_test)

# Extract predicted values
predicted_trips = test_data['trips'].values

!pip install pygam